namespace Statlyn.Core
{
    public enum PlayerFieldKey
    {
        Unknown = 0,
        SourcePlayerId = 1,
        DisplayName = 2,
        Age = 3,
        DateOfBirth = 4,
        Nationality = 5,
        NationalityFlag = 6,
        PlayerFaceImage = 7,
        Club = 8,
        League = 9,
        PrimaryPosition = 10,
        SecondaryPositions = 11,
        PreferredFoot = 12,
        Height = 13,
        Weight = 14,
        ContractEnd = 15,
        Wage = 16,
        MarketValue = 17,
        EstimatedValueRange = 18,
        Availability = 19,
        TransferStatus = 20,
        LoanStatus = 21,
        InterestLevel = 22,
        TechnicalAttribute = 23,
        PhysicalAttribute = 24,
        PlayerStat = 25,
        PhysicalData = 26,
        ScoutKnowledge = 27,
        ScoutStars = 28,
        ScoutRecommendation = 29,
        ScoutVisiblePersonalityNote = 30,
        UserNote = 31,
        LicensedExternalData = 32,
        CurrentAbility = 1000,
        PotentialAbility = 1001,
        HiddenPersonality = 1002,
        InjuryProneness = 1003,
        Consistency = 1004,
        ImportantMatches = 1005,
        Professionalism = 1006,
        Pressure = 1007,
        Ambition = 1008,
        Loyalty = 1009,
        Adaptability = 1010,
        Temperament = 1011
    }
}
